### ISSUE TITLE
Validity of integer vectors: result of division by zero

### ISSUE THREAD

**Issue by gnzlbg** [rust-rfcs/unsafe-code-guidelines#89]
I have one example from `packed_simd`, where I want to implement vertical (lane-wise) division for packed SIMD vectors (`repr(simd)`). The Intel SVML (Short-Vector Math Library) exposes these with the [`_mm_div_ep{i,u}{lane_bitwidth}`](https://software.intel.com/en-us/node/524292) APIs.

I've implemented two functions for integers:

```rust
impl Simd<[T; N]> where T: Signed | Unsigned {
    pub fn wrapping_div(self, other: Self) -> Self {
        assert!(!other.eq(Self::splat(0)).any(),
                     "division by zero: `{:?} / {:?}`", self, other);
        unsafe { intrinsic::wrapping_div(self, other) }
    }
}
```

This first function, `wrapping_div`, panics if any of the lanes of the denominator is zero, and is therefore safe. For those users that know that none of the lanes of the denominator is zero, I also implemented: 

```rust
impl Simd<[T; N]> where T: Signed | Unsigned {
    /// ... Safety: if any of the lanes of other is zero, the behavior is undefined.
    pub unsafe fn wrapping_div_unchecked(self, other: Self) -> Self {
        // debug_assert!(!other.eq(Self::splat(0)).any(),
        //             "division by zero: `{:?} / {:?}`", self, other);
        unsafe { intrinsic::wrapping_div(self, other) }
    }
}
```

When operating on SIMD vectors it is, however, very common to only care about some lanes of the result:    

```rust
let a: Simd<[i32; 4]>;
let c = unsafe { a.wrapping_div_unchecked(b) };  
let d = shuffle!(c, [0, 1]); // extract lanes 0 and 1
// drop(c); // the result of lanes 2 and 3 is never used
```

So it would be nice if instead of saying that calling `wrapping_div_unchecked` with a denominator containing a zero lane is undefined behavior, I could say something else to support this idiom. 

Would supporting uninitialized bits in integers help here? That depends what division by zero returns.

A different way of improving this API would be to change the signature of the method to: 

```rust
pub fn wrapping_div_unchecked(a: Simd<[T; N]>, b: Simd<[T; N]>)
     -> Simd<[MaybeUninit<T>; N]>;
```

The user could then write: 

```rust
let a: Simd<[i32; 4]>;
let c = a.wrapping_div_unchecked(b);  
let d: Simd<[i32; 2]> = unsafe { shuffle!(c, [0, 1]).into_inner() }; // extract lanes 0 and 1
let e: MaybeUninit<i32> = c.extract(2);
let f: i32 = unsafe { e.into_inner() }; // UB?
```

Iff we want to make step `f` UB then division by zero has to return an _invalid value_ (if the value was _valid_ then that wouldn't be UB).

From an API point-of-view I like the signature using `MaybeUninit`. It moves the `unsafe` block from the division, which from a hardware point-of-view isn't necessarily UB (although it could be, depending on the arch), to the read of the invalid value.

**Comment by rkruppe** [comment]
I don't think there's anything that can be done about this topic from the validity or more generally UCG angle. The integer division instruction in LLVM is instant UB (not undef/poison) if the divisor is zero, and that's that. If there is an alternative way to represent a division in LLVM IR that doesn't have that UB, e.g. a target-specific intrinsic, then `packed_simd` needs to decide whether it wants to use that.

**Comment by gnzlbg** [comment]
Indeed. 

> If there is an alternative way to represent a division in LLVM IR that doesn't have that UB, e.g. a target-specific intrinsic, then `packed_simd` needs to decide whether it wants to use that.

While the library could use this internally, this choice couldn't affect its API (it wouldn't be portable).
